/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frm_ATM;

import ATM_Server.ATM_Interface;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Frm_RutTien extends javax.swing.JFrame {

    private ATM_Interface atm;

    public class TuyenDoan extends Thread {

        private final ATM_Interface atm;
        private final JFrame frame;

        public TuyenDoan(ATM_Interface atm, JFrame frame) {
            this.atm = atm;
            this.frame = frame;
        }

        @Override
        public void run() {
            try {
                frame.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosing(WindowEvent e) {
                        try {
                            int result_Close = JOptionPane.showConfirmDialog(frame, "Bạn có chắc muốn đóng không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
                            if (result_Close == JOptionPane.YES_OPTION) {
                                boolean result = atm.CapNhatTrangThai_KhongHoatDong(HoTen.getText());
                                if (result) {
                                    frame.dispose(); // Đóng frame nếu chọn Yes
                                }
                            } else {
                                // Nếu chọn No, giữ frame mở
                                frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                            }
                        } catch (Exception ex) {
                            Logger.getLogger(Frm_Home.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                });
            } catch (Exception ex) {
                Logger.getLogger(Frm_LichSu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * Creates new form Frm_RutTien
     *
     * @param hoTen
     * @param soTaiKhoan
     */
    public Frm_RutTien(String hoTen, String soTaiKhoan) {
        try {
            initComponents();
            HoTen.setText(hoTen);
            SoTaiKhoan.setText(soTaiKhoan);

            Image icon = new ImageIcon(this.getClass().getResource("/icon.jpg")).getImage();
            this.setIconImage(icon);

            // Kết nối đến thanh ghi
            Registry registry = LocateRegistry.getRegistry("localhost", 1099);
            atm = (ATM_Interface) registry.lookup("ATM");

            TuyenDoan tuyenDoan = new TuyenDoan(atm, this);
            tuyenDoan.start();
        } catch (RemoteException e) {
            System.err.println("Lỗi RemoteException: " + e.getMessage());
        } catch (NotBoundException e) {
            System.err.println("Lỗi NotBoundException: " + e.getMessage());
        }
    }

    private Frm_RutTien() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        Button_Xoa = new javax.swing.JButton();
        txt_tien = new java.awt.Label();
        Button_100000 = new javax.swing.JButton();
        Button_200000 = new javax.swing.JButton();
        Button_500000 = new javax.swing.JButton();
        Button_1000000 = new javax.swing.JButton();
        Button_2000000 = new javax.swing.JButton();
        Button_NhapSoKhac = new javax.swing.JButton();
        Button_XacNhan = new javax.swing.JButton();
        Button_KetThuc = new javax.swing.JButton();
        HoTen = new java.awt.Label();
        SoTaiKhoan = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Rút Tiền");

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon.png"))); // NOI18N

        label2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("ATM BANK");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(121, 121, 121)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 184, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(199, 199, 199)
                .addComponent(jLabel2))
        );

        label3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Số tiền:");

        Button_Xoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button_Xoa.setText("Xoá");
        Button_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_XoaActionPerformed(evt);
            }
        });

        txt_tien.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_tien.setForeground(new java.awt.Color(255, 255, 255));
        txt_tien.setText("0");

        Button_100000.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_100000.setText("100.000");
        Button_100000.setActionCommand("");
        Button_100000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_100000ActionPerformed(evt);
            }
        });

        Button_200000.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_200000.setText("200.000");
        Button_200000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_200000ActionPerformed(evt);
            }
        });

        Button_500000.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_500000.setText("500.000");
        Button_500000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_500000ActionPerformed(evt);
            }
        });

        Button_1000000.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_1000000.setText("1.000.000");
        Button_1000000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_1000000ActionPerformed(evt);
            }
        });

        Button_2000000.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_2000000.setText("2.000.000");
        Button_2000000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_2000000ActionPerformed(evt);
            }
        });

        Button_NhapSoKhac.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_NhapSoKhac.setText("Nhập số khác");
        Button_NhapSoKhac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_NhapSoKhacActionPerformed(evt);
            }
        });

        Button_XacNhan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button_XacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-success-48.png"))); // NOI18N
        Button_XacNhan.setText("Xác nhận");
        Button_XacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_XacNhanActionPerformed(evt);
            }
        });

        Button_KetThuc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_KetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-back-64.png"))); // NOI18N
        Button_KetThuc.setText("Kết thúc");
        Button_KetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_KetThucActionPerformed(evt);
            }
        });

        HoTen.setForeground(new java.awt.Color(255, 255, 255));
        HoTen.setText("label4");

        SoTaiKhoan.setText("label4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_tien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Xoa)
                .addGap(116, 116, 116))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(SoTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_XacNhan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_KetThuc)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Button_1000000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_100000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button_200000, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_2000000))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Button_NhapSoKhac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_500000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Xoa)
                    .addComponent(txt_tien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_100000)
                    .addComponent(Button_200000)
                    .addComponent(Button_500000))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_2000000)
                    .addComponent(Button_1000000)
                    .addComponent(Button_NhapSoKhac))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Button_XacNhan)
                        .addComponent(Button_KetThuc))
                    .addComponent(SoTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getDate() {
        Calendar calendar = Calendar.getInstance();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDate = dateFormat.format(calendar.getTime());
        return formattedDate;
    }

    int tien = 0;
    private void Button_100000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_100000ActionPerformed
        // TODO add your handling code here:
        tien = 100000 + Integer.parseInt(txt_tien.getText());
        txt_tien.setText(String.valueOf(tien));
    }//GEN-LAST:event_Button_100000ActionPerformed

    private void Button_200000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_200000ActionPerformed
        // TODO add your handling code here:
        tien = 200000 + Integer.parseInt(txt_tien.getText());
        txt_tien.setText(String.valueOf(tien));
    }//GEN-LAST:event_Button_200000ActionPerformed

    private void Button_500000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_500000ActionPerformed
        // TODO add your handling code here:
        tien = 500000 + Integer.parseInt(txt_tien.getText());
        txt_tien.setText(String.valueOf(tien));
    }//GEN-LAST:event_Button_500000ActionPerformed

    private void Button_1000000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_1000000ActionPerformed
        // TODO add your handling code here:
        tien = 1000000 + Integer.parseInt(txt_tien.getText());
        txt_tien.setText(String.valueOf(tien));
    }//GEN-LAST:event_Button_1000000ActionPerformed

    private void Button_2000000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_2000000ActionPerformed
        // TODO add your handling code here:
        tien = 2000000 + Integer.parseInt(txt_tien.getText());
        txt_tien.setText(String.valueOf(tien));
    }//GEN-LAST:event_Button_2000000ActionPerformed

    private void Button_XacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_XacNhanActionPerformed
        // TODO add your handling code here:
        String usename = HoTen.getText();
        String tien = txt_tien.getText();
        String soTaiKhoan = SoTaiKhoan.getText();
        try {
            boolean result = atm.ruttien(usename, Long.parseLong(tien));
            boolean themlichsugiaodich = atm.ThemLichSu(getDate(), Long.parseLong(tien), soTaiKhoan, "NULL", HoTen.getText());
            if (result && themlichsugiaodich) {
                JOptionPane.showMessageDialog(this, "Rút tiền thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Không đủ số dư!");
            }
        } catch (Exception ex) {
            Logger.getLogger(Frm_RutTien.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage(), "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        }
        txt_tien.setText("0");
    }//GEN-LAST:event_Button_XacNhanActionPerformed

    private void Button_KetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_KetThucActionPerformed
        // TODO add your handling code here:
        Frm_Home frm_home = null;
        frm_home = new Frm_Home(HoTen.getText(), SoTaiKhoan.getText());
        frm_home.show();
        this.dispose();
    }//GEN-LAST:event_Button_KetThucActionPerformed

    private void Button_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_XoaActionPerformed
        // TODO add your handling code here:
        txt_tien.setText("0");
    }//GEN-LAST:event_Button_XoaActionPerformed

    private void Button_NhapSoKhacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_NhapSoKhacActionPerformed
        // TODO add your handling code here:
        Frm_NhapSoTienCanRut frm_nhapsotiencanrut = null;
        frm_nhapsotiencanrut = new Frm_NhapSoTienCanRut(HoTen.getText(), SoTaiKhoan.getText());
        frm_nhapsotiencanrut.show();
        this.dispose();
    }//GEN-LAST:event_Button_NhapSoKhacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Frm_RutTien().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_100000;
    private javax.swing.JButton Button_1000000;
    private javax.swing.JButton Button_200000;
    private javax.swing.JButton Button_2000000;
    private javax.swing.JButton Button_500000;
    private javax.swing.JButton Button_KetThuc;
    private javax.swing.JButton Button_NhapSoKhac;
    private javax.swing.JButton Button_XacNhan;
    private javax.swing.JButton Button_Xoa;
    private java.awt.Label HoTen;
    private java.awt.Label SoTaiKhoan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label txt_tien;
    // End of variables declaration//GEN-END:variables
}
